### ISSUE TITLE
Issues for afcon2022-cameroon

### ISSUE THREAD

**Issue by MrkarlosM** [abongsjoel/afcon2022-cameroon#2]
This is an Issues section to review code of the project by the team 161.

**Comment by MrkarlosM** [comment]
You have done a great job here Joel, please don't forget to think about the other pages names in order to include them in the `href` of your `index.html`.

**Comment by MrkarlosM** [comment]
You could also use `sticky-top` bootstrap's class in order to get your nav-bar stuck at the top while scrolling.

**Comment by alexisbec** [comment]
This is just a recommendation: try to keep all the styles of a media query inside of that media query instead of creating more than one media query of the same size. This is to avoid the reviewers getting confused searching for the elements inside of one specific version.
